name: Feature
description: Create a new feature implementation task
title: "[Feature]: "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to create a feature issue!
        
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Brief description of the feature to be implemented
      placeholder: Describe the feature here...
    validations:
      required: true

  - type: textarea
    id: technical-requirements
    attributes:
      label: Technical Requirements
      description: List the technical requirements for this feature
      placeholder: |
        - [ ] Requirement 1
        - [ ] Requirement 2
        - [ ] Requirement 3
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: List the acceptance criteria for this feature
      placeholder: |
        - [ ] Criteria 1
        - [ ] Criteria 2
        - [ ] Criteria 3
    validations:
      required: true

  - type: dropdown
    id: story-points
    attributes:
      label: Story Points
      description: Select the story points for this feature
      options:
        - 1
        - 2
        - 3
        - 5
        - 8
        - 13
    validations:
      required: true

  - type: textarea
    id: additional-notes
    attributes:
      label: Additional Notes
      description: Any additional information, context, or references
      placeholder: Add any other context here...
    validations:
      required: false
